import dotenv from "dotenv";
dotenv.config();
console.log('Environment PORT:', process.env.PORT);
export const {
  PORT,
  MONGO_URI,
  EASEBUZZ_KEY,
  EASEBUZZ_SALT,
  EASEBUZZ_ENV,
  EASEBUZZ_IFRAME,
  JWT_SECRET,
  JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET,
  JWT_ACCESS_EXPIRES_IN,
  JWT_REFRESH_EXPIRES_IN,
  NODE_ENV,
  USER_EMAIL,
  USER_PASSWORD,
  FRONTEND_URL,
  BACKEND_URL,
  RATE_LIMIT_WINDOW_MS,
  RATE_LIMIT_MAX,
  AUTH_RATE_LIMIT_MAX,
  OTP_RATE_LIMIT_MAX,
} = process.env;
